#!/usr/bin/env bash
#transfers a file from our client to a server.
ssh_options="-o StrictHostKeyChecking=no"

if [ $# -ge 4 ]
then
	scp $ssh_options -i "$4" "$1" "$3"@"$2":~
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
