#!/usr/bin/env bash
#configure Nginx to redirect the /redirect_it location to another page
sudo apt-get update -y
sudo apt-get install nginx -y
echo "<!DOCTYPE html>
<head>
<title>Hello World!
</title>
</head>
<body>Hello World!</body>
</html> =" | sudo tee /var/www/html/index.html
sudo sed -i '/server {/a \ location /redirect_me {\return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4/ew_page;\}' /etc/nginx/nginx.conf
sudo service nginx restart
