#!/usr/bin/env bash
#a custom 404 page that contains the string 
sudo apt-get update -y
sudo apt-get install nginx -y
echo "<!DOCTYPE html>
<head>
<title>Hello World!
</title>
</head>
<body>Hello World!</body>
</html> =" | sudo tee /var/www/html/index.html
website="www.youtube.com/watch?v=QH2-TGUlwu4"
sudo sed -i '/server {/a \ location /redirect_me {\return 301 http://$website/new_page;\}' /etc/nginx/nginx.conf
echo "Ceci n'est pas une page" | sudo tee /var/www/html/index.html
sudo service nginx restart
