#!/usr/bin/env bash
#A bash script that install nginx
sudo apt-get update -y
sudo apt-get install nginx -y
echo "<!DOCTYPE html>
<head>
<title>Hello World!
</title>
</head>
<body>Hello World!</body>
</html>" | sudo tee /var/www/html/index.html
custom_header="a add_header X-server-by"
path="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _/$custom_header $HOSTNAME:" $path
nginx -t && service nginx reload
