#!/usr/bin/env bash
#A bash script that install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

echo "<!DOCTYPE html>
<head>
<title>Hello World!
</title>
</head>
<body>Hello World!</body>
</html>" | sudo tee /var/www/html/index.html

#This Configures a custom response HTTP header.
path="/etc/nginx/sites-available/default"
sudo sed -i "/server_name _/a add_header X-server-by $HOSTNAME;" $path
#Check for 
sudo nginx -t
#Restart nginx
sudo service nginx restart
