#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.
sudo apt-get install -y haproxy
echo "ENABLED=1" >> /etc/default/haproxy

configure_haproxy(){
        echo "" >> /etc/haproxy/haproxy.cfg
        echo "backend mybackend" >> /etc/haproxy/haproxy.cfg
        echo "server 459245-web-01 35.153.67.140 check" >> /etc/haproxy/haproxy.cfg
        echo "server 459245-web-02 54.227.199.5 check" >> /etc/haproxy/haproxy.cfg
service haproxy start
