#!/usr/bin/env bash
#Bash script that displays To infinity and beyond
#With a sleep 2, display I am invincible!!! when receiving a SIGTERM signal.
trap 'echo "I am invincible!!!"' SIGTERM
while [[ true ]] ; do
	sleep 2
	echo "To infinity and beyond"
done
