#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 100
#Displays FizzBuzz if the multiple of 3 and 5
#Displays Fizz if the multiple of 3
#Displays Buzz if the multiple of 5
i=1
while [ $i -le 100 ]
do
	if (( i % 3 == 0 && i % 5 == 0 )); then
                echo "FizzBuzz"
	elif (( i % 3 == 0 )); then
                echo "Fizz"
	elif (( i % 5 == 0 )); then
                echo "Buzz"
        else
                echo $i
        fi
        (( i++ ))
done
