#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
file=/etc/passwd
while IFS=: read -r user enpass uid gid desc home shell; do
        [ $uid ] && echo "The user $user is part of the $uid gang, lives in $home and rides $shell. $uid's place is protected by the passcode x, more info about the user here: $user"
done < "$file"
