#!/usr/bin/env bash
#A Bash script that displays Best School
#bad luck on the 4 loop iteration
#good luck on the 8 loop iteration
i=1
while [ $i -le 10 ]
do
	if [ $i == 4 ]; then
		echo "bad luck"
	elif [ $i == 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
        (( i++ ))
done
