#!/usr/bin/env bash
#A Bash script that displays numbers from 1 to 20
#Displays bad luck from china on the 4 iteration
#Displays bad luck from Japan on the 9 iteration
#Displays bad luck from Italy on the 17 iteration
i=1
while [ $i -le 20 ]
do
	echo $i
	case $i in
		"4")
			echo "bad luck from China"
			;;
		"9")
			echo "bad luck from Japan"
			;;
		"17")
			echo "bad luck from Italy"
			;;
	esac
        (( i++ ))
done
