#!/usr/bin/env bash
#This script changes the user name from www-data to nginx.
sudo sed -i "s/www-data/nginx/" /etc/nginx/nginx.conf
#nginx must be listening on all active IPs on port 8080.
sudo sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo service nginx start
